### ISSUE TITLE
Add issue templates to repositories

### ISSUE THREAD

**Issue by Thesourtimes** [fosscord/fosscord#103]
Recently I saw several invalid-labeled issues and premade templates could be good a solution to decrase number of them and make It easier for people to ask, suggest, report and answer. For now templates for 4 actions specified above might be enough.

**Comment by popeda97** [comment]
https://github.com/fosscord/fosscord/issues/90#issue-984899524

**Comment by popeda97** [comment]
> Recently I saw several invalid-labeled issues and premade templates could be good a solution to decrase number of them and make It easier for people to ask, suggest, report and answer. For now templates for 4 actions specified above might be enough.
