### ISSUE TITLE
Use the boomerang logo

### ISSUE THREAD

**Issue by erkinalp** [fosscord/fosscord#114]
The boomerang logo, unlike game controller logo, cannot be confused with Discord Inc.'s logo.

**Comment by Intevel** [comment]
A new logo is already in work, we are currently waiting for the response from the current project leaders.

**Comment by ChrisChrome** [comment]
> A new logo is already in work, we are currently waiting for the response from the current project leaders.

Yes they know, they're referring to this one![image](https://user-images.githubusercontent.com/28414320/147839735-9119bcda-3e08-4616-a1b8-a3fea1dbd8c8.png)
