### ISSUE TITLE
Remove fosscord instance from list until complete

### ISSUE THREAD

**Issue by R030t1** [fosscord/fosscord#115]
Right now it looks like a password harvesting site, if you're not done with everything you should take it down.

**Comment by ImAaronFR** [comment]
password harvesting site...? can you explain more lol?

**Comment by R030t1** [comment]
From https://fosscord.com/instances/, click on https://app.fosscord.com/. Attempting to sign up does nothing. If it's not working it probably shouldn't be there.

**Comment by ImAaronFR** [comment]
> From https://fosscord.com/instances/, click on https://app.fosscord.com/. Attempting to sign up or log in does nothing. If it's not working it probably shouldn't be there.

i mean it's not done yet and idk how it looks like a password harvesting site but you got a point there sooo

**Comment by Intevel** [comment]
@ImAaronFR he mean's a phishing site.
