### ISSUE TITLE
Running Fosscord without Internet access

### ISSUE THREAD

**Issue by pivinx1** [fosscord/fosscord#124]
I'd like to run my Fosscord instance with no internet access, but as soon as I cut the connection to the outside Internet, I can't do much with it, as it loses connection with some sort of service. How can I do it so Fosscord doesn't use any services using Internet access, or at least make it so Internet access isn't required?

**Comment by ImAaronFR** [comment]
I'm not sure if this is possible or not but just save the assets of client and change the path in the index file and test it

**Comment by TheArcaneBrony** [comment]
Not recommended as it requires storing discord's proprietary client code on your server.
