### ISSUE TITLE
Voice Chat isnt working.

### ISSUE THREAD

**Issue by Adithr123** [fosscord/fosscord#126]
Whenever I try to join the VC channels, it simply says connecting, stays like that for a few seconds, then disconnects. I don't know if VC's have been fully implemented, but that would be fun to see.

**Comment by ImAaronFR** [comment]
It's not implemented yet, It'll be implemented in the future tho

**Comment by Adithr123** [comment]
Okay, thnks!

**Comment by gnouts** [comment]
Maybe we can keep this open to track progress ? It was what I tried on my first connection running fosscord ^^
