### ISSUE TITLE
Author avatar not showing on messages

### ISSUE THREAD

**Issue by pikachub2005** [fosscord/fosscord#148]
Did you guys know about this?
![Screenshot 2022-03-13 9 11 58 PM](https://user-images.githubusercontent.com/74213212/158088658-e3a950d4-8ffb-4d1d-a8df-9f750d51fa90.png)

**Comment by moon2u22** [comment]
You need to change Message display in Apperance

**Comment by pikachub2005** [comment]
> You need to change Message display in Apperance

Okay, thanks
