### ISSUE TITLE
[Feature] RPC for developers

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord#17]
it would be great if someone makes a RPC script for the devs that displays all useful information about this project to reach more devs to work on this, thank you :)

**Comment by BuilderHD** [comment]
Add Easter Egg 🥚
I have image
https://cdn.discordapp.com/attachments/785912702467178527/807685864637202442/IMG_9gc6sd.jpg

**Comment by xNaCly** [comment]
[RPC] url-buttons not working @TimSchweiz

**Comment by Flam3rboy** [comment]
done by @TimSchweiz
