### ISSUE TITLE
[Feature] Patreon/Funding

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord#18]
Donation page to maintain server costs and other expenses

**Comment by BuilderHD** [comment]
I need send patreon?

**Comment by Flam3rboy** [comment]
no xD, for others who use the server/client to support the project and the devs

**Comment by Flam3rboy** [comment]
but wait, is there a feature called money pool, that gets send to the individual dev patreon accs?

**Comment by BuilderHD** [comment]
okay XD )

**Comment by Flam3rboy** [comment]
done https://opencollective.com/fosscord
