### ISSUE TITLE
How to change default permissions to be like discord?

### ISSUE THREAD

**Issue by CosmicStar98** [fosscord/fosscord#180]
title explains it all.
I want to set the default permissions to be like discord instead of not being able to do anything

**Comment by Hoot679** [comment]
ask in their discord server

**Comment by SurpriseLon** [comment]
> title explains it all. I want to set the default permissions to be like discord instead of not being able to do anything

You can use [DBserver](https://dbeaver.io/) to implement setting the default values, or you can use the following SQL command in the terminal
`ALTER TABLE public.users ALTER COLUMN rights SET DEFAULT 648540060672;`

**Comment by javaarchive** [comment]
This is also available as a config option in the config table, forgot the name of it
will edit if I come across it again later today.
