### ISSUE TITLE
Fosscord Servers (Guilds) stop working after a moment

### ISSUE THREAD

**Issue by Eevee-Gaming** [fosscord/fosscord#190]
Hi ! I'm having a problem with [the Fosscord testing instance](https://staging.fosscord.com/).
Weirdly, it's seems that every server you create, just, stop working after.
We still can see the servers, the channels, but **we actually can't send messages**. _Even can't see the chat..._
![7ACxrTjeU](https://user-images.githubusercontent.com/106253650/208456264-5bab95ab-734c-45c9-b793-91a15174511d.jpg)
It just say this. I refreshed a couple of time, waited (it work, but sometimes, not.), but actually nothing. It always do this problem when i try to create one.
And it affects every users. Plus, invites dosen't work after...

It seems that everything dosen't respond, even the users are being forget.
![ATxmx_BOG](https://user-images.githubusercontent.com/106253650/208457193-37cdf35e-d274-48b0-9aeb-f5589a29fa6e.jpg)
The banner dosen't show. And the Nitro badge is removed and just a exclamation point is showed saying blah blah blah we can't load.

I don't really know if that is doing that for everyone, but for me, yeah, everytime.

So well, that's it. I use the testing server because my computer still uses Windows 7, and i **can't run anything for a server**. Sorry for that.
_My english is not really good, sorry for that too. If you don't understand something, lemme know._

Have a good day !

**Comment by Eevee-Gaming** [comment]
Update : My server is working again with some wait. 
I just still do not want to close the issue, because i want to know why this bug is happening.
_It can be possible that my server CRASH again, so that's another reponse to why i don't want to close._

**Comment by SurpriseLon** [comment]
> Hi ! I'm having a problem with [the Fosscord testing instance](https://staging.fosscord.com/). Weirdly, it's seems that every server you create, just, stop working after. We still can see the servers, the channels, but **we actually can't send messages**. _Even can't see the chat..._ ![7ACxrTjeU](https://user-images.githubusercontent.com/106253650/208456264-5bab95ab-734c-45c9-b793-91a15174511d.jpg) It just say this. I refreshed a couple of time, waited (it work, but sometimes, not.), but actually nothing. It always do this problem when i try to create one. And it affects every users. Plus, invites dosen't work after...
> 
> It seems that everything dosen't respond, even the users are being forget. ![ATxmx_BOG](https://user-images.githubusercontent.com/106253650/208457193-37cdf35e-d274-48b0-9aeb-f5589a29fa6e.jpg) The banner dosen't show. And the Nitro badge is removed and just a exclamation point is showed saying blah blah blah we can't load.
> 
> I don't really know if that is doing that for everyone, but for me, yeah, everytime.
> 
> So well, that's it. I use the testing server because my computer still uses Windows 7, and i **can't run anything for a server**. Sorry for that. _My english is not really good, sorry for that too. If you don't understand something, lemme know._
> 
> Have a good day !

This is most likely a problem with your network

**Comment by javaarchive** [comment]
Hello, just curious for steps to repro did any of you do something to update your account before this happended, like change profile pictures?

**Comment by Eevee-Gaming** [comment]
> Did any of you do something to update your account before this happended, like change profile pictures?

I think not for mine but some on my server yeah i think.

**Comment by Eevee-Gaming** [comment]
> This is most likely a problem with your network

Not sure. On every device that is not owner, it keep doing this.
But if i switch to the owner, it works. But the members are on _undefined_.

**Comment by Eevee-Gaming** [comment]
**UPDATE :** After some hard time, i decided to kick every member, and reinvite them. And. All works fine now.
But i'm not sure if this happens again.
I just want to know what does this.

**Comment by javaarchive** [comment]
I believe it has to do with people losing `@everyone` role in the database but I have not traced the section of code that does this. Apparently this is a side effect of recent changes in staging.

**Comment by Puyodead1** [comment]
> I believe it has to do with people losing `@everyone` role in the database but I have not traced the section of code that does this. Apparently this is a side effect of recent changes in staging.

a fix for that was already merged https://github.com/fosscord/fosscord-server/pull/906

**Comment by TheArcaneBrony** [comment]
If this is incorrect, let us know!
