### ISSUE TITLE
It crashed

### ISSUE THREAD

**Issue by aChenForLife** [fosscord/fosscord#192]
I tried clearing my cookies and all that but every time I visit the website it says: Well this is awkward... Looks like Fosscord has crashed unexpectedly...

**Comment by TheArcaneBrony** [comment]
Is this on staging.fosscord.com, and do you happen to have any DMs open?

**Comment by aChenForLife** [comment]
yes I do

**Comment by aChenForLife** [comment]
i works now idk why

**Comment by TheArcaneBrony** [comment]
i forgot to reply, but ive updated the instance because we had accidentally broken the READY payload, causing the client to crash due to not being able to find some field in the user object of private DMs

**Comment by aChenForLife** [comment]
Awesome, thanks!
