### ISSUE TITLE
catagories not showing when setting up discovery

### ISSUE THREAD

**Issue by ThomasBOIisbest** [fosscord/fosscord#199]
When I set up Discovery, no categories show up, which means I cant do Discovery. Please help.

**Comment by Puyodead1** [comment]
Well, did you set any categories up on the database? Lol

**Comment by ThomasBOIisbest** [comment]
what database?

**Comment by Puyodead1** [comment]
> what database?
https://docs.fosscord.com/setup/server/database/

**Comment by ThomasBOIisbest** [comment]
Thx.
