### ISSUE TITLE
No free software license

### ISSUE THREAD

**Issue by nfitzen** [fosscord/fosscord#20]
Currently this project can't be called Open Source or [free software] since it doesn't have a license that meets any of the 2 criteria (or even at all).

Just in case, if you want a recommendation, I'd recommend [`AGPL-3.0-or-later`] for the server and [`GPL-3.0-or-later`] for the client. If you want extensions to be able to remain proprietary, then [`LGPL-3.0-or-later`] is fine for the client, too. These would ensure that the project remains free software.

[`AGPL-3.0-or-later`]: https://spdx.org/licenses/AGPL-3.0-or-later.html
[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html
[`LGPL-3.0-or-later`]: https://spdx.org/licenses/LGPL-3.0-or-later.html

By the way, all contributors would need to agree to licensing their existing contributions under whatever license you choose. (This step doesn't need to be done in the future thanks to GitHub's ToS.)

(IANAL, this is not legal advice.)

[free software]: https://www.gnu.org/philosophy/free-sw.html "Software where the users have the freedom to run, copy, distribute, study, change, and improve the software"

**Comment by Flam3rboy** [comment]
explained here: 
https://github.com/fosscord/fosscord-client/issues/22

**Comment by Flam3rboy** [comment]
everything is now licensed under GPL V3
except for [fosscord-ui](https://github.com/fosscord/fosscord-ui/issues/27), it is licensed under MIT for e.g. bot dashboards
