### ISSUE TITLE
Open demo button on website has a dead link

### ISSUE THREAD

**Issue by MathMan05** [fosscord/fosscord#204]
The link https://fosscord.com/ here is dead when you click "Open Demo" with the error "Cannot GET /"

**Comment by Puyodead1** [comment]
> The link https://fosscord.com/ here is dead when you click "Open Demo" with the error "Cannot GET /"

its not "dead", its an API, theres no front end webpage for it anymore as the test client was removed. the demo button needs to be removed

**Comment by Puyodead1** [comment]
![image](https://user-images.githubusercontent.com/14828766/226152563-0adfa99d-bf68-49da-ac5f-6d3d06446cc2.png)

**Comment by MathMan05** [comment]
The button still has a dead link, the url should either be updated to the new client or be temporarly be removed

**Comment by MaddyUnderStars** [comment]
I could've sworn I did update the website to link to the new client. Super weird how there's no commits, did someone force push or smth? Anyway I'll check it out later

**Comment by geisterfurz007** [comment]
The link now points to a mail login with a bad certificate; is this intended? A link to https://fosscord.com is still present here in this repository.

**Comment by MaddyUnderStars** [comment]
Thanks. We'll be updating all links, repos and whatever else to use our new name and domain name soon:tm:
