### ISSUE TITLE
[Feature] Custom Themes

### ISSUE THREAD

**Issue by Superbug50** [fosscord/fosscord#25]
_It would be nice if the user was able to use a custom made theme's from the community or they can make their own._
-----
anyways...
Please fix the readme link because it leads to a 404 page @Flam3rboy 
https://github.com/fosscord/fosscord/tree/main/setup

"Or if you want to setup all repositories have a look at the [Readme](https://github.com/fosscord/fosscord/tree/main/setup)"
"_Originally posted by @Flam3rboy in https://github.com/fosscord/fosscord/issues/10#issuecomment-808923289_"
![image](https://user-images.githubusercontent.com/25424568/115578621-50c91f80-a27a-11eb-8e40-70f21d9c5256.png)

**Comment by Flam3rboy** [comment]
yes this will definitely be added
