### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Stylix58** [fosscord/fosscord#28]
I should think I can start the making of a website for Fosscord.

**Frontend:**
HTML, CSS, JS

**Backend:**
NodeJS (?):
- Express (?)
- Vue (??)

or

Python 3 (??):
- Flask

**Comment by xNaCly** [comment]
Although we appreciate the effort. We already have a website: fosscord.com

**Comment by Flam3rboy** [comment]
Have a look at the [Contribution Guide](https://github.com/fosscord/fosscord/wiki/Contribution)
And choose the repository you want to work on.
Server or client side?
Also for easier communication just dm me on discord 😄

**Comment by Stylix58** [comment]
OK

**Comment by Stylix58** [comment]
I will migrate this issue to https://github.com/fosscord/fosscord-landingpage
