### ISSUE TITLE
what the hell is a network

### ISSUE THREAD

**Issue by kalebplayz125** [fosscord/fosscord#37]
im trying to signup/ login but it says i need a network  i pt in fosccord.com and it didnt even show

**Comment by Flam3rboy** [comment]
the current client at app.fosscord.com doesn’t work yet

**Comment by kalebplayz125** [comment]
> the current client at app.fosscord.com doesn’t work yet

but i saw isues talk about stuff from in the app like features!

**Comment by Flam3rboy** [comment]
It’s in development and not yet published

**Comment by kalebplayz125** [comment]
> It’s in development and not yet published

oh... :(

**Comment by kalebplayz125** [comment]
sry for bothering i just really wanted to try it out

**Comment by Flam3rboy** [comment]
You can setup the dev version if you know what you are doing
https://docs.fosscord.com/contributing/

**Comment by kalebplayz125** [comment]
> You can setup the dev version if you know what you are doing
> https://docs.fosscord.com/contributing/

idk but ill try

**Comment by kalebplayz125** [comment]
what languge is it made in

**Comment by kalebplayz125** [comment]
JavaScript

C++

C# / .NET

Go

Java

C

Perl

PHP

Python

Ruby

Scala
or
Other

**Comment by Flam3rboy** [comment]
TypeScript, basically a superset of JavaScript

**Comment by kalebplayz125** [comment]
so do i go with other or javascript on mongodb

**Comment by Flam3rboy** [comment]
wdym? we use JavaScript and mongodb for datastorage

**Comment by kalebplayz125** [comment]
![Screenshot 2021-05-15 103135](https://user-images.githubusercontent.com/71709962/118374484-c7e79000-b568-11eb-87c1-dc1b5c467474.png)


> wdym? we use JavaScript and mongodb for datastorage

**Comment by Flam3rboy** [comment]
Just skip

**Comment by kalebplayz125** [comment]
k

**Comment by kalebplayz125** [comment]
is a shared cluster fine?

**Comment by Flam3rboy** [comment]
Yes should be

**Comment by kalebplayz125** [comment]
which one 
AWS
Google cloud
or
Azure

**Comment by Flam3rboy** [comment]
I think AWS is free

**Comment by kalebplayz125** [comment]
they arent all free?

**Comment by Flam3rboy** [comment]
idk you should be able to see which are free

**Comment by kalebplayz125** [comment]
on all of them on the bottom left it said free

**Comment by Flam3rboy** [comment]
k

**Comment by kalebplayz125** [comment]
so which one is the best

**Comment by Flam3rboy** [comment]
AWS

**Comment by kalebplayz125** [comment]
k

**Comment by kalebplayz125** [comment]
is 512 mb enough?

**Comment by kalebplayz125** [comment]
@Flam3rboy

**Comment by Flam3rboy** [comment]
Yes for the start

**Comment by kalebplayz125** [comment]
what should i name the cluster

**Comment by Flam3rboy** [comment]
idk choose one

**Comment by kalebplayz125** [comment]
(its funny how we are in a closed issue instead of general the actual discord server)

**Comment by kalebplayz125** [comment]
ima name it fosscord-cloud

**Comment by Flam3rboy** [comment]
You can join it https://discord.gg/UFkeRXGcSh

**Comment by kalebplayz125** [comment]
> You can join it https://discord.gg/UFkeRXGcSh

way ahead of u

**Comment by kalebplayz125** [comment]
i did about a hour ago

**Comment by kalebplayz125** [comment]
we should talk in the discord instead
