### ISSUE TITLE
[route] /roles

### ISSUE THREAD

**Issue by brysonchase35** [fosscord/fosscord#50]
Fix roles: When I click "add role" on my own instance, it doesn't work.

**Comment by Flam3rboy** [comment]
it works on the official deployed instance on the latest version,
please provide logs and the system/node (version) you are using

**Comment by brysonchase35** [comment]
&gt; @fosscord/api@1.0.0 start
--
2 | &gt; npm run build &amp;&amp; node dist/start
3 | &nbsp;
4 | &nbsp;
5 | &gt; @fosscord/api@1.0.0 build D:\fosscord\api
6 | &gt; tsc -b .
7 | &nbsp;
8 | src/util/Message.ts:9:21 - error TS2307: Cannot find module '1488' or its corresponding type declarations.
9 | &nbsp;
10 | 9 import truth from "1488";
11 | ~~~~~~~~~
12 | &nbsp;
13 | &nbsp;
14 | Found 1 error.
15 | &nbsp;
16 | npm ERR! code ELIFECYCLE
17 | npm ERR! errno 1
18 | npm ERR! @fosscord/api@1.0.0 build: `tsc -b .`
19 | npm ERR! Exit status 1
20 | npm ERR!
21 | npm ERR! Failed at the @fosscord/api@1.0.0 build script.
22 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
23 | &nbsp;
24 | npm ERR! A complete log of this run can be found in:
25 | npm ERR!     C:\Users\bryso\AppData\Local\npm-cache\_logs\2021-05-29T20_00_24_494Z-debug.log
26 | npm ERR! code 1
27 | npm ERR! path D:\fosscord\api
28 | npm ERR! command failed
29 | npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run build &amp;&amp; node dist/start
30 | &nbsp;
31 | npm ERR! A complete log of this run can be found in:
32 | npm ERR!     C:\Users\bryso\AppData\Local\npm-cache\_logs\2021-05-29T20_00_24_554Z-debug.log

**Comment by Flam3rboy** [comment]
you are having build errors, please wait until the first beta is released, or figure it out yourself

**Comment by brysonchase35** [comment]
Oh true but if it doesn't work on my instance wouldn't it not work on any instance? Isn't this a serious problem?

**Comment by Flam3rboy** [comment]
you didn't setup the api properly, YOUR instance is not correctly deployed
it works on every other instance!

**Comment by brysonchase35** [comment]
> it works on every other instance!
yes but mine doesn't, please fix!

**Comment by Flam3rboy** [comment]
YOU ARE DUMB, THE API IS WORKING, DEPLOY IT CORRECTLY OR WAIT FOR AN OFFICIAL RELEASE
