### ISSUE TITLE
[Feature] Cross-Instance communication

### ISSUE THREAD

**Issue by IdotMaster1** [fosscord/fosscord#53]
Just a way for a self-hosted server could communicate with another one so for example a guy on one server can chat with another guy on a completely different server.

**Comment by Flam3rboy** [comment]
This will be done through the client, not through cross-instance communication so that no third party can intercept/intervene messages

**Comment by brysonchase43** [comment]
> Just a way for a self-hosted server could communicate with another one so for example a guy on one server can chat with another guy on a completely different server.

So like I would be able to chat from my fosscord client to your fosscord client without visiting your client

**Comment by IdotMaster1** [comment]
> > Just a way for a self-hosted server could communicate with another one so for example a guy on one server can chat with another guy on a completely different server.
> 
> So like I would be able to chat from my fosscord client to your fosscord client without visiting your client

Kinda

**Comment by brysonchase43** [comment]
That would be cool
