### ISSUE TITLE
Add forum

### ISSUE THREAD

**Issue by Stylix58** [fosscord/fosscord#56]
I think this is a good idea to make a forum for help people who don't have Discord. We can use something like [Flarum](https://flarum.org) or [Discourse](https://www.discourse.org).

**Comment by Flam3rboy** [comment]
no they should use github discussions

**Comment by xNaCly** [comment]
agreed @Flam3rboy

**Comment by Shayshon** [comment]
Github discussions isn't the best for forums.

**Comment by Flam3rboy** [comment]
thats why we use discord

**Comment by Shayshon** [comment]
Not everyone has discord, plus your discord is kinda a mess. Just saying it wasn't a terrible suggestion

**Comment by xNaCly** [comment]
maybe a lightweight simple forum would be good, moderation is still a pain as seen on the discord

**Comment by Flam3rboy** [comment]
Only general xD
but the other channels are well structured

**Comment by Shayshon** [comment]
True, but your discord is super unmoderated and still a bit of a mess. If you had a forum you could easily filter out the good from bad

**Comment by xNaCly** [comment]
i disagree, a discord server will be always unmoderated. 
But also i dont want to moderate a forum or a discord server due to me not having the nerves to deal with these kinda people nor having the time to do so

**Comment by Flam3rboy** [comment]
we do not moderate either discord nor forums, just in special cases

**Comment by Shayshon** [comment]
There are people with an 8,000 member discord that can moderate better. The use of racial slurs in the discord are unbelievable. But if you had a forum, you could have a bot easily filter most things out

**Comment by Flam3rboy** [comment]
we could also have a discord bot that filter most things

**Comment by Shayshon** [comment]
> we do not moderate either discord nor forums, just in special cases

If you don't mod the discord, it will get banned 😅

**Comment by xNaCly** [comment]
so what, we dont need the discord for anything and honestly moderating this clusterfuck is just a waste of time

**Comment by Flam3rboy** [comment]
but we did choose not to do so
As I said in special cases when someone raise any issue we'll take action

**Comment by Shayshon** [comment]
> so what, we dont need the discord for anything and honestly moderating this clusterfuck is just a waste of time
> 

It'll get banned, along with the owner... then you won't have a discord.

**Comment by Flam3rboy** [comment]
> If you don't mod the discord, it will get banned 😅

Another showcase where a company forces rules on you, wheter you like them or not, and another reason to use fosscord instead.

**Comment by xNaCly** [comment]
> It'll get banned, along with the owner... then you won't have a discord.
why tf along with the owner?

**Comment by Shayshon** [comment]
> but we did choose not to do so
> As I said in special cases when someone raise any issue we'll take action

So if someone was saying a bunch of racist things, even as a joke, you wouldn't do anything unless someone yelled in your dms?

**Comment by xNaCly** [comment]
oh no a joke :clown_face:

**Comment by Shayshon** [comment]
> oh no a joke :clown_face: 

Racism is still Racism.

**Comment by xNaCly** [comment]
if a joke doesnt offend someone its not funny

**Comment by Shayshon** [comment]
> if a joke doesnt offend someone its not funny

No offense, but are you racist or do you just not realize what you said?

**Comment by xNaCly** [comment]
:raised_eyebrow: where is the problem with jokes to a certain extend?

**Comment by Shayshon** [comment]
> :raised_eyebrow: where is the problem with jokes to a certain extend?

Most of the "jokes" in the fosscord server go way beyond jokes. Plus there's also lots of spam and actual racist, undesirable people there.

**Comment by xNaCly** [comment]
> Most of the "jokes" in the fosscord server go way beyond jokes. Plus there's also lots of spam and actual racist, undesirable people there. 

The jokes im reading on the server are tasteless i agree but following our dogma we tolerate everything except directed attacks.

**Comment by Shayshon** [comment]
> > Most of the "jokes" in the fosscord server go way beyond jokes. Plus there's also lots of spam and actual racist, undesirable people there. 
> 
> The jokes im reading on the server are tasteless i agree but following our dogma we tolerate everything except directed attacks.

So you will tolerate racist and spammers as long as people aren't dming you about it?

**Comment by xNaCly** [comment]
> So you will tolerate racist and spammers as long as people aren't dming you about it?
Thats not what i said, i said i will tolerate jokes which arent directly aimed at other users or groups of users

**Comment by Stylix58** [comment]
> maybe a lightweight simple forum would be good, moderation is still a pain as seen on the discord

What forum you should use so?

**Comment by Shayshon** [comment]
> > So you will tolerate racist and spammers as long as people aren't dming you about it?
> 
> Thats not what i said, i said i will tolerate jokes which arent directly aimed at other users or groups of users

Then why is it in the server? Why can't you just hire mods if you're understaffed?

**Comment by xNaCly** [comment]
> Then why is it in the server? Why can't you just hire mods if you're understaffed?
Hire? with what money? This is a FOSS projekt, we dont really make money.

**Comment by Shayshon** [comment]
> > Then why is it in the server? Why can't you just hire mods if you're understaffed?
> 
> Hire? with what money? This is a FOSS projekt, we dont really make money.

There are plenty of people who would volunteer. Make an announcement on the discord or github.

**Comment by Flam3rboy** [comment]
If you have any issues please report them and we'll take action.

**Comment by ItsNewe** [comment]
> > > Then why is it in the server? Why can't you just hire mods if you're understaffed?
> > 
> > 
> > Hire? with what money? This is a FOSS projekt, we dont really make money.
> 
> There are plenty of people who would volunteer. Make an announcement on the discord or github.

The subject of moderation is completely unrelated to the development of fosscord and to this issue. Go whine elsewhere, don't pollute the git.

**Comment by robigan** [comment]
Haha am polluting the git 🥵🥵🤡 (Am sorry I had to do this lol)

**Comment by DodoGames7** [comment]
rip
