### ISSUE TITLE
LICENSE text

### ISSUE THREAD

**Issue by TechnologyClassroom** [fosscord/fosscord#60]
I see the LICENSE file contains a license header for AGPL-3.0-only.  I would recommend that text be moved to a `License` subheading in the README file at least and the LICENSE file should contain the entirety of the AGPLv3 license.  The benefit of this change is that LICENSE would be more obvious and displayed in the first page view of the GitHub project.

I would be happy to make a PR for this change.

**Comment by Flam3rboy** [comment]
Sure 👍
