### ISSUE TITLE
[Bug] Cannot access http://localhost:3001 when using Docker

### ISSUE THREAD

**Issue by DonaldKellett** [fosscord/fosscord#67]
Following the setup outlined in https://docs.fosscord.com/contributing.html , I executed the following commands on Ubuntu 20.04 server with Docker installed and running and the current user added to the `docker` group (so no `sudo` is required):

```bash
$ git clone --recurse-submodules -j8 https://github.com/fosscord/fosscord
$ cd fosscord
$ git submodule foreach "git checkout master && git pull origin master"
$ docker-compose up
```

After waiting for a few minutes to stabilize, running `$ docker container ls` gives me the following output indicating the services are up and running:

```
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS                      NAMES
c8ba84cffee1   fosscord_fosscord-api       "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes   0.0.0.0:3001->3001/tcp     api
ede3cc550fe7   fosscord_fosscord-gateway   "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes   0.0.0.0:3002->3002/tcp     gateway
463773e75603   mongo                       "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes   0.0.0.0:27017->27017/tcp   mongo
```

However, when I try to access http://localhost:3001 using `curl`, I get (same for port 3002):

```bash
$ curl http://localhost:3001
curl: (56) Recv failure: Connection reset by peer
```

https://serverfault.com/a/769583 suggested that this error may be due to the service listening to a port other than 3001, so I peered inside both containers from the `fosscord_fosscord-api` and `fosscord_fosscord-gateway` images and get:

```bash
$ docker container exec -it c8ba84cffee1 /bin/sh
# netstat -an | grep LISTEN
tcp        0      0 127.0.0.11:37439        0.0.0.0:*               LISTEN      
```

```bash
$ docker container exec -it ede3cc550fe7 /bin/sh
# netstat -an | grep LISTEN
tcp        0      0 127.0.0.11:34517        0.0.0.0:*               LISTEN      
```

So it seems that the API server and gateway are listening to random high-numbered ports instead of the intended ports 3001-3002. Or am I mistaken?

**Comment by Flam3rboy** [comment]
the api probably didn't start, might be related to #66

**Comment by Flam3rboy** [comment]
closed due to inactivity
