### ISSUE TITLE
Support database encryption

### ISSUE THREAD

**Issue by erkinalp** [fosscord/fosscord#68]
Data protection law requires personally identifying data should not be accessible to service operators in plain form unless absolutely required. Hence, the database should be made to allow at-rest symmetric and/or end-to-end public key homomorphic encryption.

**Comment by Flam3rboy** [comment]
Already possible, but you need to configure your mongodb database to use TLS/SSL:
https://docs.mongodb.com/manual/tutorial/configure-ssl/
https://docs.mongodb.com/manual/core/security-transport-encryption/
and specify the certificate in the connection string
https://docs.mongodb.com/manual/reference/connection-string/#tls-options
