### ISSUE TITLE
Login and Register Transition does not perform correctly

### ISSUE THREAD

**Issue by BrickUniverses** [fosscord/fosscord#71]
Comparison:
Discord Client:
https://user-images.githubusercontent.com/45805828/125001748-b6b58e00-e096-11eb-9ede-0d5436299d3c.mp4
Fosscord:
https://user-images.githubusercontent.com/45805828/125001525-368f2880-e096-11eb-9f7a-a096cb2fcad2.mp4

**Comment by Flam3rboy** [comment]
This is just the demo client and not our fosscord client

**Comment by BrickUniverses** [comment]
👍

**Comment by DairyWeb3638077** [comment]
👍
