### ISSUE TITLE
Direct Messages List Reverts to 'Loading State' on Load

### ISSUE THREAD

**Issue by BrickUniverses** [fosscord/fosscord#73]
Instead of showing your 'Direct Messages' (I know DMs have not been added yet) it shows this:
![Screen Shot 2021-07-09 at 9 24 12 am](https://user-images.githubusercontent.com/45805828/125002094-86222400-e097-11eb-901b-0f5821483e71.png)

**Comment by Flam3rboy** [comment]
this is normal, even discord shows it like this, if you don't have any dms
