### ISSUE TITLE
Active Now Does Nothing

### ISSUE THREAD

**Issue by BrickUniverses** [fosscord/fosscord#74]
When you click 'Count Me In!' it does not do anything, (no dialog or anything)
![Screen Shot 2021-07-09 at 9 26 30 am](https://user-images.githubusercontent.com/45805828/125002222-c84b6580-e097-11eb-834a-e8df1eab6be9.png)

**Comment by Flam3rboy** [comment]
because its the demo and the science route is not done yet
https://github.com/fosscord/fosscord-api/issues/140
