### ISSUE TITLE
Audit Log Spinner gones into Infinite Loop

### ISSUE THREAD

**Issue by BrickUniverses** [fosscord/fosscord#75]
Audit Log Spinner goes into Infinite Loop as shown below:
(Your database supports the Audit Log however)
![Screen Shot 2021-07-09 at 9 28 44 am](https://user-images.githubusercontent.com/45805828/125002412-32640a80-e098-11eb-8ca8-5b419a04fe70.png)

**Comment by Flam3rboy** [comment]
not implemented yet
