### ISSUE TITLE
Discord TOS

### ISSUE THREAD

**Issue by zgast** [fosscord/fosscord#91]
Even if this is a really early state and nobody knows how Discord will handle this (I hope to not see u in front of the judge), but myb it would make sense to implement a way to login without the discord account to be safe that you can use fosscord without getting eventually banned from discord.

**Comment by Flam3rboy** [comment]
yes we plan to have multiple ways of authentication:
- OAuth2 (login with Fosscord/Discord/Google)
- Federated (login with accounts from other instances (like matrix))
- Decentralized (create a new account with username/password which are only stored on your instance)

**Comment by Featyre** [comment]
Add something to the issue: check out the 2nd to last question from [this](https://gist.github.com/meew0/a3168b8fbb02d5a5456a06461b9e829e)
![image](https://user-images.githubusercontent.com/88265031/132676778-ade02adf-8f45-46d0-b4bd-21a04034f47a.png)

**Comment by Featyre** [comment]
> Well, @Featyre it depends. Discord only bans accounts out of nowhere if they act maliciously. Also, Discord doesn't care which client/client mods you use, as long as you use the API correctly, because they only see the API interactions and nothing more.
> 
> If a Discord account acts maliciously, they make an automated decision based on the Account's trustworthiness (afaik).
> 
> What does acting maliciously mean? Poor usage of the API. E. g., no cookies, fingerprint, overuse of specific routes etc.
> 
> > Discord won't just ban people out of the blue.
> 
> They do if you use the API wholly wrong and your Account is untrusted (young Account age, no phone number, no verified mail, etc.).
> 
> > does it make sense for Discord to ban someone instantly? No!
> 
> Yes, it makes sense! What if a token gets abused for spamming? Discord must stop such spam directly, and Discord will only give a second chance if the user opens a support ticket and gives a good explanation (e. g., hijacked token).
> 
> > they should notice the user before they decided to ban them.
> 
> If an old account with a clean record acts maliciously, they will password lock your Account. So, they will send you mail telling you that someone maybe hijacked your Account, and it is locked until you change your password.
> 
> So as long as Fosscord uses the Discord API properly, Discord can't notice that a user is using a different client hence no user will be banned out of nowhere.

Reading from this reply I should expand what i talked about: at that time i didn't consider malicious users into modded client users/custom client users, and I do agree that they ban users who use API maliciously, it just doesn't make sense to ban users who are not (and using modded clients).

Also I hope Fosscord (the client) uses Discord API as an official client does.
