### ISSUE TITLE
crashed when trying to start up the server

### ISSUE THREAD

**Issue by ArgentArcent** [fosscord/fosscord#96]
you know self explanatory on the title asking for answers not angry

**Comment by Stilic** [comment]
What is the error you get when it's happen?

**Comment by ArgentArcent** [comment]
so first i just opn the app up wait a couple of seconds and its gone simple as that

**Comment by Stilic** [comment]
You don't have a console opened when you open the server?

**Comment by ArgentArcent** [comment]
yep if it could i can make a gif when it is demonstarting what my problem is  hold on

**Comment by Stilic** [comment]
Ok, do the gif so.

**Comment by ArgentArcent** [comment]
encoding the sharex file

**Comment by ArgentArcent** [comment]
oh great the gif is dead

**Comment by Stilic** [comment]
?

**Comment by Stilic** [comment]
You can join our discord also:
https://discord.gg/ZrnGQP6p3d

**Comment by ArgentArcent** [comment]
like the gif got corrupted

**Comment by Stilic** [comment]
I can't help you for this xd

**Comment by ArgentArcent** [comment]
rip
